---
- name: Install Android tools
  community.general.snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items:
    - android-studio
    - flutter
  become: True

- name: Install common snap tools
  community.general.snap:
    name: "{{ item }}"
    state: present
  with_items:
    - skype
  become: True

